#!/bin/bash
rm -r /opt/manjaro/tools/manjaro-applications-discovery/
rmdir /opt/manjaro/tools/manjaro-applications-discovery/
cd /opt/manjaro/tools/
git clone https://gitlab.manjaro.org/webpage/manjaro-applications-discovery
mkdir -p /opt/manjaro/tools/manjaro-applications-discovery/src/static/images/appstream/icons
mkdir -p /opt/manjaro/tools/manjaro-applications-discovery/src/static/images/appstream/flathub
ln -sf /usr/share/app-info/icons/* /opt/manjaro/tools/manjaro-applications-discovery/src/static/images/appstream/icons
ln -sf /var/lib/flatpak/appstream/flathub/x86_64/active/icons/64x64/* /opt/manjaro/tools/manjaro-applications-discovery/src/static/images/appstream/flathub
cp /opt/manjaro/tools/manjaro-applications-discovery/updateDiscover /usr/bin